// Copyright 2015 The Go Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Toolstash provides a way to save, run, and restore a known good copy of the Go toolchain
// and to compare the object files generated by two toolchains.
//
// Usage:
// https://github.com/golang/go/wiki/cgo#global-functions
// globalfunc is simple use Go and C export func
//	(Go:globalfunc.go) AGoFunction()
//			export AGoFunction for C
//		|
//	(C:globalfunc.c) printf "ACFunction()" and call AGoFunction()
//			"ACFunction" is native "C". "AGoFunction" is import from "Go"
//		|
//	(C:globalfunc.go) extern void ACFunction();
//			import native "C" func to "Go"
//		|
//	(Go:globalfunc.go) Example()
//			call C.ACFunction in "Go"
//		|
//	(Go:main.go) call Example()
//			call Example(). Example() including AGoFunction() also ACFunction();

package main

import "github.com/zchee/cgo/globalfunc/gf"

// call gf.Example()
func main() {
	gf.Example()
}
